### ISSUE TITLE
Issue using this

### ISSUE THREAD

**Issue by BryantIT** [2sh/vcf-to-23andme#3]
This is the error code I get when I attempt to use this to convert my data

"Traceback (most recent call last): File "data_to_db.py", line 11, in csv.field_size_limit(sys.maxsize) OverflowError: Python int too large to convert to C long"

**Comment by 2sh** [comment]
I had responded to your email and committed a fix for this 2 days ago. Please try it.

In case the email got lost, what I said was that the issue seems to be that on some computers "sys.maxsize" is too large, so putting "csv.field_size_limit(2**20)" in place should fix the issue for you.

The line is there because some of the VCF CSV file values are really long and cause the CSV parser to raise an exception. So a quick solution I'd found is setting the limit to something higher and sys.maxsize was suggested. Setting it to something lower such as 2**20 still gets around the issue, tested with my own VCF file, and it shouldn't cause your overflow issue anymore.

Thanks for reporting the issue.

**Comment by BryantIT** [comment]
Thank you! No I didn't get the other email but I'll try this solution
today.

**Comment by 2sh** [comment]
@BryantIT Did you test it?
